spring:
  application:
    name: exchange-conversion
     
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8100

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka