spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8765