spring:
  application:
    name: exchange-service
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true

management:
  tracing:
    sampling:
      probability: 1.0
      
server:
  port: 8000

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka